# Generated by Django 3.2.11 on 2022-02-27 09:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TrackingSystem', '0003_contributors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issues',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                                           primary_key=True,
                                           serialize=False,
                                           verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('description', models.CharField(max_length=550)),
                ('tag', models.CharField(max_length=550)),
                ('priority', models.CharField(max_length=550)),
                ('status', models.CharField(max_length=550)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('assigned_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                    related_name='assigned_user',
                                                    to=settings.AUTH_USER_MODEL)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                             to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                              related_name='issues',
                                              to='TrackingSystem.project')),
            ],
        ),
    ]
