# Generated by Django 3.2.11 on 2022-03-03 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TrackingSystem', '0004_issues'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contributors',
            name='permission',
        ),
    ]
